# Generated by Django 5.0.6 on 2024-05-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer'),
        ),
    ]
