# Generated by Django 5.0.6 on 2024-05-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliveryrequest_user_deliveryrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='denied', max_length=10),
        ),
    ]
