# Generated by Django 5.0.6 on 2024-06-05 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliveryrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='item_name',
            field=models.CharField(default='NOT SPECIFIED', max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='payment_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
