# Generated by Django 5.0.6 on 2024-06-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliveryrequest_assigned_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('accepted', 'Accepted'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
