# Generated by Django 5.0.6 on 2024-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliveryrequest_date_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='sender_email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
