# Generated by Django 5.0.6 on 2024-05-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_user_alter_userwallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
